export const services = [
  { id: 'staffing', number: '01', title: 'IT Staffing', label: 'The right people. The right fit.', description: 'Connect your business with technology talent that brings the skills, mindset, and ambition to move it forward.', detail: 'From specialist project roles to permanent teams, we align talent with your technical requirements and business culture.', points: ['Contract & permanent hiring', 'Specialist technology talent', 'Candidate screening & placement'], icon: 'users' },
  { id: 'training', number: '02', title: 'Training Programs', label: 'Build skills for what comes next.', description: 'Practical, industry-focused learning that turns potential into capability—and capability into opportunity.', detail: 'Develop technical confidence through structured learning, hands-on practice, and guidance tailored to your career goals.', points: ['Technical skill development', 'Hands-on project learning', 'Industry-aligned learning paths'], icon: 'graduation' },
  { id: 'career', number: '03', title: 'Career Development', label: 'Your ambition. A clear direction.', description: 'Navigate your next career move with thoughtful guidance, interview preparation, and a plan built around you.', detail: 'Bring clarity to your career journey with support that helps you communicate your strengths and prepare for opportunities.', points: ['Career planning & guidance', 'Resume & profile development', 'Interview preparation'], icon: 'arrow' },
  { id: 'cloud', number: '04', title: 'Cloud Solutions', label: 'A stronger foundation for growth.', description: 'Build a more agile business with cloud solutions designed around your operations, your people, and your future.', detail: 'Plan your cloud journey with a focus on reliable infrastructure, considered migration, and ongoing optimization.', points: ['Cloud strategy & migration', 'Infrastructure & integration', 'Performance optimization'], icon: 'cloud' },
] as const;
export const industries = [
  { title: 'Technology', description: 'Talent and cloud capabilities for software, digital products, and IT services.' },
  { title: 'Healthcare', description: 'Technology expertise to support connected care and efficient operations.' },
  { title: 'Finance', description: 'Specialist skills for evolving financial platforms and digital services.' },
  { title: 'Retail & E-commerce', description: 'People and technology that support seamless commerce experiences.' },
  { title: 'Education', description: 'Digital skills and technology support for modern learning environments.' },
  { title: 'Manufacturing', description: 'Technology talent and infrastructure for connected, efficient operations.' },
];
export const articles = [
  { category: 'CAREER INSIGHTS', title: 'Your next career move starts with a clearer plan', summary: 'A considered approach to finding your direction in technology.', body: ['Start by identifying the work you enjoy and the problems you want to solve. Compare your current strengths with the requirements of roles that interest you.', 'Choose one or two skill gaps to focus on. Build a small practical project that demonstrates those skills, and explain your contribution clearly on your profile.', 'Prepare examples of how you solve problems, collaborate, and learn. A focused plan makes your next step more intentional.'], image: 'team' },
  { category: 'CLOUD & TECHNOLOGY', title: 'Building a cloud strategy around your business', summary: 'Why business goals should lead every technology decision.', body: ['A cloud strategy begins with an understanding of your operations—not a choice of platform. Identify the workloads, dependencies, and business outcomes that matter most.', 'Evaluate security, availability, cost, and governance before migrating. Some workloads benefit from a phased approach rather than moving everything at once.', 'Define how performance and spend will be measured. Review those measures regularly as your business evolves.'], image: 'cloud' },
];
export function pageHead(title: string, description: string) { return { meta: [{ title: `${title} | VANDRO Private Limited` }, { name: 'description', content: description }, { property: 'og:title', content: `${title} | VANDRO Private Limited` }, { property: 'og:description', content: description }, { property: 'og:type', content: 'website' }, { name: 'twitter:card', content: 'summary_large_image' }] }; }
