import { createFileRoute, Link } from '@tanstack/react-router';
import { useEffect, useRef, useState } from 'react';
import { ArrowUpRight, ArrowDown, Pause, Play, Check, Globe2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { SiteLayout, SectionLabel, ConnectBand } from '@/components/site/layout';
import { ServicesGrid } from '@/components/site/services';
import { pageHead, industries, articles } from '@/lib/site-content';
import video from '@/assets/vandro-hero.webm.asset.json';
import poster from '@/assets/hero-poster.jpg';
import team from '@/assets/team.jpg';
import cloud from '@/assets/cloud.jpg';
export const Route = createFileRoute('/')({head: () => pageHead('Talent. Technology. Transformation.', 'VANDRO brings IT staffing, practical training, career development, and cloud solutions together to help people and businesses move forward.'), component: Home});
function Home() {
 const videoRef = useRef<HTMLVideoElement>(null); const [playing, setPlaying] = useState(false);
 useEffect(() => { if (!window.matchMedia('(prefers-reduced-motion: reduce)').matches) videoRef.current?.play().catch(() => setPlaying(false)); }, []);
 function toggleVideo() {const el = videoRef.current; if (!el) return; if (el.paused) el.play().catch(() => setPlaying(false)); else el.pause();}
 return <SiteLayout><section className="hero"><img className="hero-media" src={poster} alt="Technology professionals collaborating in a modern office" width={1920} height={1024}/><video ref={videoRef} className="hero-media" src={video.url} poster={poster} muted loop playsInline onPlay={() => setPlaying(true)} onPause={() => setPlaying(false)} aria-label="VANDRO technology and talent brand film"/><div className="hero-shade"/><div className="shell hero-content"><SectionLabel>PEOPLE. TECHNOLOGY. POSSIBILITY.</SectionLabel><h1>VANDRO<span>Talent. Technology.<br/><em>Transformation.</em></span></h1><p>Connecting ambitious people and forward-thinking<br className="desktop-break"/> businesses to what comes next.</p><Button asChild size="lg"><Link to="/services">Discover our solutions <ArrowUpRight/></Link></Button></div><div className="shell hero-bottom"><a href="#what-we-do" className="scroll-link"><ArrowDown size={16}/> Explore VANDRO</a><span>YOUR AMBITION. OUR COMMITMENT.</span><Button size="icon" variant="ghost" className="video-control" onClick={toggleVideo} aria-label={playing ? 'Pause background video' : 'Play background video'}>{playing ? <Pause/> : <Play/>}</Button></div></section>
 <section className="services-section" id="what-we-do"><div className="shell"><div className="section-heading"><div><SectionLabel>WHAT WE DO</SectionLabel><h2>Built for your<br/><span>next move.</span></h2></div><div className="section-heading-right"><p>Great talent. Relevant skills. Smarter technology.<br/>Four ways we help you move forward.</p><Link to="/services" className="text-link">All our services <ArrowUpRight size={18}/></Link></div></div><ServicesGrid/></div></section>
 <section className="about-section"><div className="shell about-grid"><div className="about-image"><img src={team} alt="Professionals working together on a technology project" width={1536} height={1024} loading="lazy"/><div className="image-caption"><span>CONNECTED BY PEOPLE.</span><span>DRIVEN BY POSSIBILITIES.</span></div></div><div className="about-copy"><SectionLabel>THE VANDRO APPROACH</SectionLabel><h2>Progress starts<br/>with <span>people.</span></h2><p>Behind every business breakthrough is the right team. Behind every career milestone is the right opportunity.</p><p>At VANDRO Private Limited, we bring the two together—connecting talent, building capabilities, and making technology work for your ambitions.</p><div className="about-values"><span><Check/>People-first thinking</span><span><Check/>Purpose-led solutions</span></div><Link to="/about" className="text-link">Get to know VANDRO <ArrowUpRight size={18}/></Link></div></div></section>
 <section className="industries-section"><div className="shell"><div className="section-heading"><div><SectionLabel>INDUSTRIES WE SERVE</SectionLabel><h2>Different industries.<br/><span>Shared ambition.</span></h2></div><div className="section-heading-right"><Globe2 className="industry-globe" size={46} strokeWidth={1}/><p>A thoughtful approach to the unique challenges<br/>of every sector.</p></div></div><div className="industry-grid">{industries.map((item,i) => <Link to="/industries" key={item.title}><span className="industry-index">0{i+1}</span><h3>{item.title}</h3><ArrowUpRight size={20}/></Link>)}</div></div></section>
 <section className="process-section"><div className="shell"><SectionLabel>HOW WE WORK</SectionLabel><div className="section-heading"><h2>A clear path.<br/><span>A meaningful partnership.</span></h2><p>From the first conversation to the next milestone,<br/>we stay focused on what matters to you.</p></div><div className="process-grid">{[{t:'Understand',d:'We listen to your goals, your challenges, and where you want to go.'},{t:'Connect',d:'We identify the talent, expertise, or learning path that fits your needs.'},{t:'Prepare',d:'We align skills, evaluate readiness, and build a foundation for success.'},{t:'Move forward',d:'We support your next step and keep the conversation going.'}].map((x,i)=><div key={x.t}><span className="process-number">0{i+1}<span/></span><h3>{x.t}</h3><p>{x.d}</p></div>)}</div></div></section>
 <section className="insights-section"><div className="shell"><div className="section-heading"><div><SectionLabel>IDEAS & PERSPECTIVES</SectionLabel><h2>A little perspective.<br/><span>A lot of possibility.</span></h2></div><Link className="text-link" to="/resources">Explore resources <ArrowUpRight size={18}/></Link></div><div className="insights-grid">{articles.map((a,i)=><Link to="/resources" hash={`article-${i}`} key={a.title} className="insight-card"><img src={a.image==='team'?team:cloud} alt={a.image==='team'?'Technology team collaborating':'Cloud server infrastructure'} width={1536} height={1024} loading="lazy"/><div><span>{a.category}</span><h3>{a.title}</h3><ArrowUpRight/></div></Link>)}</div></div></section><ConnectBand/></SiteLayout>
}
